version: '3'
services:
  db:
    image: postgres
    expose:
      - "5432"
  nightingale:
    image: adammitre/nightingale:connectathon19-01
    ports:
      - "80:3000"
    depends_on:
      - db
  smart:
    image: adammitre/nightingale-smart:connectathon19-02
    ports:
      - "81:80"
  canary:
    image: adammitre/canary:02-04-19
    ports:
      - "82:80"
